### ISSUE TITLE
Publish package in PyPI

### ISSUE THREAD

**Issue by reingart** [PyAr/pyafipws#106]
We need a new GitHub Action workflow to automatically publish this package to [PyPI](https://pypi.org/) (Python Package Index)

This will be useful for other project, to ease their installation.
For example see a thread for the Odoo Argentine localization: https://github.com/reingart/pyafipws/issues/102

How-To: 
https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

The GitHub Action [pypa/gh-action-pypi-publish](https://github.com/pypa/gh-action-pypi-publish) could be easily added to `.github//workflows/python-package.yml`:
```
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
```
This action should only run if `secrets.TEST_PYPI_API_TOKEN` is configured
