### ISSUE TITLE
Windows Installers

### ISSUE THREAD

**Issue by reingart** [PyAr/pyafipws#109]
Initial work has been done in `.github/workflows/windows_installer.yml` to compile and build the installers for windows with `py2exe`.

Further work is needed to create an one-click NSIS installer (see `setup_win.py`) and [nsis.py](https://github.com/pyar/pyafipws/blob/main/nsis.py)

This process should be fully automated in GitHub Actions, publishing a new release with the executable installer each time a PR is merged.

Manual procedure to build installers are documented in the [wiki](https://github.com/reingart/pyafipws/wiki/InstalacionCodigoFuente#generaci%C3%B3n-de-instalador)

**Comment by HanslettTheDev** [comment]
Alright so here is a proof of concept I have come up with

**Comment by HanslettTheDev** [comment]
Here is a sample of what I think can help create the release
Below is a brief explanation of how it works


The `build job` performs the following steps:
  - Checks out the code from the repository.
  - Installs the dependencies required for building the installer.
  - Builds the one file Windows installer using py2exe.
  - Uploads the installer as a release asset to the GitHub release.

The `publish job` depends on the build job. It performs the following steps:
  - Creates a new GitHub release using the tag name of the merged pull request.
  - Retrieves the ID of the created release.
  - Downloads the installer asset from the build job.
  - Uploads the installer as a release asset to the newly created GitHub release

```yaml
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install py2exe
          pip install -r requirements.txt
      - name: Build installer
        run: |
          python setup.py py2exe
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/installer.exe
          asset_name: installer.exe
          asset_content_type: application/octet-stream

  publish:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Get release ID
        id: get_release_id
        run: echo "::set-output name=release_id::$(echo ${{ steps.create_release.outputs.release_id }} | sed 's/[^0-9]*//g')"
      - name: Download installer asset
        id: download_asset
        uses: actions/download-artifact@v2
        with:
          name: installer
          path: dist/
      - name: Upload installer asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/installer.exe
          asset_name: installer.exe
          asset_content_type: application/octet-stream
```
